source 'http://rubygems.org'

group :development do
  gem 'debase', require: false
  gem 'rake', require: false
  gem 'rubocop', require: false
  gem 'ruby-debug-ide', require: false
  gem 'travis-lint', require: false
  gem 'simplecov', require: false
end

gem 'cucumber'
gem 'rspec'
gem 'capybara'
gem 'selenium-webdriver'
gem 'site_prism'
gem 'require_all'
gem 'pry'
gem 'allure-cucumber'
gem 'logger'